In [1]:
import numpy as np

In [26]:
arr = np.array([(1,2,5,4),(5,6,5,8)])

In [27]:
print(arr)

[[1 2 5 4]
 [5 6 5 8]]


In [28]:
arr.ndim

2

In [29]:
arr.itemsize

4

In [30]:
arr

array([[1, 2, 5, 4],
       [5, 6, 5, 8]])

In [31]:
type(arr)

numpy.ndarray

In [32]:
d = [23,43]

In [33]:
type(d)

list

In [34]:
arr.dtype

dtype('int32')

In [35]:
arr.shape

(2, 4)

In [37]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [5, 5],
       [4, 8]])

In [42]:
arr.reshape(4,2)

array([[1, 2],
       [5, 4],
       [5, 6],
       [5, 8]])

In [55]:
np.linspace(1,4,25)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ,
       2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   , 3.125,
       3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [57]:
arr.max()

8

In [58]:
arr.min()

1

In [59]:
arr.mean()

4.5

In [60]:
arr.sum()

36

In [63]:
np.sqrt(arr)

array([[1.        , 1.41421356, 2.23606798, 2.        ],
       [2.23606798, 2.44948974, 2.23606798, 2.82842712]])

In [66]:
np.linspace(4, 2, 52)

array([4.        , 3.96078431, 3.92156863, 3.88235294, 3.84313725,
       3.80392157, 3.76470588, 3.7254902 , 3.68627451, 3.64705882,
       3.60784314, 3.56862745, 3.52941176, 3.49019608, 3.45098039,
       3.41176471, 3.37254902, 3.33333333, 3.29411765, 3.25490196,
       3.21568627, 3.17647059, 3.1372549 , 3.09803922, 3.05882353,
       3.01960784, 2.98039216, 2.94117647, 2.90196078, 2.8627451 ,
       2.82352941, 2.78431373, 2.74509804, 2.70588235, 2.66666667,
       2.62745098, 2.58823529, 2.54901961, 2.50980392, 2.47058824,
       2.43137255, 2.39215686, 2.35294118, 2.31372549, 2.2745098 ,
       2.23529412, 2.19607843, 2.15686275, 2.11764706, 2.07843137,
       2.03921569, 2.        ])

In [67]:
np.std(arr)

2.0615528128088303

In [69]:
(1,2,3)+(4,5,6)

(1, 2, 3, 4, 5, 6)

In [70]:
[4,5,6]+[5,6,2]

[4, 5, 6, 5, 6, 2]

In [71]:
arr+arr

array([[ 2,  4, 10,  8],
       [10, 12, 10, 16]])

In [72]:
arr

array([[1, 2, 5, 4],
       [5, 6, 5, 8]])

In [74]:
arr(arr)

TypeError: 'numpy.ndarray' object is not callable

In [75]:
print(arr, arr)

[[1 2 5 4]
 [5 6 5 8]] [[1 2 5 4]
 [5 6 5 8]]


In [76]:
arr.vstack(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'vstack'

In [78]:
np.vstack((arr, arr))

array([[1, 2, 5, 4],
       [5, 6, 5, 8],
       [1, 2, 5, 4],
       [5, 6, 5, 8]])

In [79]:
np.hstack((arr, arr))

array([[1, 2, 5, 4, 1, 2, 5, 4],
       [5, 6, 5, 8, 5, 6, 5, 8]])

In [83]:
[[23,24],[34,45]] + [[46,68],[67,86]]

[[23, 24], [34, 45], [46, 68], [67, 86]]

In [85]:
np.exp((arr), 3)

TypeError: return arrays must be of ArrayType

In [88]:
np.log(arr)

array([[0.        , 0.69314718, 1.60943791, 1.38629436],
       [1.60943791, 1.79175947, 1.60943791, 2.07944154]])